# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers :
        default :
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public/"

    filter_sets :
        cache : ~
         # the name of the "filter set"
        small_index :
            # adjust the image quality to 75%
            quality : 75
            # list of transformations to apply (the "filters")
            filters :
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [150, 150], mode : outbound }

        index :
            quality : 75
            filters :
                thumbnail  : { size : [225, 225], mode : outbound }

        show :
            quality : 75
            filters :
                thumbnail  : { size : [300, 300], mode : outbound }

        show_first :
            quality : 90
            filters :
                thumbnail  : { size : [500, 500], mode : outbound }

        long :
            quality : 100
            filters :
                thumbnail  : { size : [300, 500], mode : outbound }

        small_landscape :
            quality : 75
            filters: 
                thumbnail  : { size : [300, 204], mode : outbound }

        landscape :
            quality : 75
            filters: 
                thumbnail  : { size : [1000, 640], mode : outbound }

