<?php

namespace App\DataFixtures\Tests;

use DateTimeImmutable;
use App\Entity\Category;
use App\Entity\SubCategory;
use App\Entity\TranslatableText;
use App\Entity\TranslatableString;
use Doctrine\Persistence\ObjectManager;
use Doctrine\Bundle\FixturesBundle\Fixture;

class CategoryTestFixtures extends Fixture
{
   
    public function load(ObjectManager $manager)
    {
        $category = (new Category)
                    ->setName(
                        (new TranslatableString)
                        ->setEn('Category 1')
                        ->setFr('Catégorie 1')
                        ->setEs('Categoria 1')
                        ->setIt('Categoria 1')
                    )
                    ->setSlug(
                        (new TranslatableString)
                        ->setEn('category-1')
                        ->setFr('categorie-1')
                        ->setEs('categoria-1')
                        ->setIt('categoria-1')
                    )
                    ->setPicture('picture.jpg')
                    ->setSmallPicture('picture_small.jpg')
                    ->setPictureAlt(
                        (new TranslatableString)
                        ->setEn('balise alt en anglais')
                        ->setFr('balise alt en français')
                        ->setEs('balise alt en espagnol')
                        ->setIt('balise alt en italien')
                    )
                    ->setMetaDescription(
                        (new TranslatableString)
                        ->setEn('méta-description en anglais')
                        ->setFr('méta-description en français')
                        ->setEs('méta-description en espagnol')
                        ->setIt('méta-description en italien')
                    )
                    ->setShortDescription(
                        (new TranslatableString)
                        ->setEn('description courte en anglais')
                        ->setFr('description courte en français')
                        ->setEs('description courte en espagnol')
                        ->setIt('description courte en italien')
                    )
                    ->setLongHtmlDescription(
                        (new TranslatableText)
                        ->setEn('description longue en anglais')
                        ->setFr('description longue en français')
                        ->setEs('description longue en espagnol')
                        ->setIt('description longue en italien')
                    )
                    ->addSubCategory(
                        (new SubCategory)
                        ->setName(
                            (new TranslatableString)
                            ->setEn('Subcategory 1')
                            ->setFr('Sous-catégorie 1')
                            ->setEs('Sobrecategoria 1')
                            ->setIt('Sopracategoria 1')
                        )
                        ->setSlug(
                            (new TranslatableString)
                            ->setEn('sub-category-1')
                            ->setFr('sous-categorie-1')
                            ->setEs('sobre-categoria-1')
                            ->setIt('sopra-categoria-1')
                        )
                        ->setPicture('picture.jpg')
                        ->setSmallPicture('picture_small.jpg')
                        ->setPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setSmallPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setMetaDescription(
                            (new TranslatableString)
                            ->setEn('méta-description en anglais')
                            ->setFr('méta-description en français')
                            ->setEs('méta-description en espagnol')
                            ->setIt('méta-description en italien')
                        )
                        ->setShortDescription(
                            (new TranslatableString)
                            ->setEn('description courte en anglais')
                            ->setFr('description courte en français')
                            ->setEs('description courte en espagnol')
                            ->setIt('description courte en italien')
                        )
                        ->setLongHtmlDescription(
                            (new TranslatableText)
                            ->setEn('description longue en anglais')
                            ->setFr('description longue en français')
                            ->setEs('description longue en espagnol')
                            ->setIt('description longue en italien')
                        )
                        ->setCreatedAt(new DateTimeImmutable())
                    )
                    ->addSubCategory(
                        (new SubCategory)
                        ->setName(
                            (new TranslatableString)
                            ->setEn('Subcategory 2')
                            ->setFr('Sous-catégorie 2')
                            ->setEs('Sobrecategoria 2')
                            ->setIt('Sopracategoria 2')
                        )
                        ->setSlug(
                            (new TranslatableString)
                            ->setEn('sub-category-2')
                            ->setFr('sous-categorie-2')
                            ->setEs('sobre-categoria-2')
                            ->setIt('sopra-categoria-2')
                        )
                        ->setPicture('picture.jpg')
                        ->setSmallPicture('picture_small.jpg')
                        ->setPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setSmallPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setMetaDescription(
                            (new TranslatableString)
                            ->setEn('méta-description en anglais')
                            ->setFr('méta-description en français')
                            ->setEs('méta-description en espagnol')
                            ->setIt('méta-description en italien')
                        )
                        ->setShortDescription(
                            (new TranslatableString)
                            ->setEn('description courte en anglais')
                            ->setFr('description courte en français')
                            ->setEs('description courte en espagnol')
                            ->setIt('description courte en italien')
                        )
                        ->setLongHtmlDescription(
                            (new TranslatableText)
                            ->setEn('description longue en anglais')
                            ->setFr('description longue en français')
                            ->setEs('description longue en espagnol')
                            ->setIt('description longue en italien')
                        )
                        ->setCreatedAt(new DateTimeImmutable())
                    )
                    ->addSubCategory(
                        (new SubCategory)
                        ->setName(
                            (new TranslatableString)
                            ->setEn('Subcategory 3')
                            ->setFr('Sous-catégorie 3')
                            ->setEs('Sobrecategoria 3')
                            ->setIt('Sopracategoria 3')
                        )
                        ->setSlug(
                            (new TranslatableString)
                            ->setEn('sub-category-3')
                            ->setFr('sous-categorie-3')
                            ->setEs('sobre-categoria-3')
                            ->setIt('sopra-categoria-3')
                        )
                        ->setCreatedAt(new DateTimeImmutable())
                        ->setPicture('picture.jpg')
                        ->setSmallPicture('picture_small.jpg')
                        ->setPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setSmallPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setMetaDescription(
                            (new TranslatableString)
                            ->setEn('méta-description en anglais')
                            ->setFr('méta-description en français')
                            ->setEs('méta-description en espagnol')
                            ->setIt('méta-description en italien')
                        )
                        ->setShortDescription(
                            (new TranslatableString)
                            ->setEn('description courte en anglais')
                            ->setFr('description courte en français')
                            ->setEs('description courte en espagnol')
                            ->setIt('description courte en italien')
                        )
                        ->setLongHtmlDescription(
                            (new TranslatableText)
                            ->setEn('description longue en anglais')
                            ->setFr('description longue en français')
                            ->setEs('description longue en espagnol')
                            ->setIt('description longue en italien')
                        )
                    )
                    ->setCreatedAt(new DateTimeImmutable())
                    ;
        $manager->persist($category);

        $category = (new Category)
                    ->setName(
                        (new TranslatableString)
                        ->setEn('Category 2')
                        ->setFr('Catégorie 2')
                        ->setEs('Categoria 2')
                        ->setIt('Categoria 2')
                    )
                    ->setSlug(
                        (new TranslatableString)
                        ->setEn('category-2')
                        ->setFr('categorie-2')
                        ->setEs('categoria-2')
                        ->setIt('categoria-2')
                    )
                    ->setPicture('picture.jpg')
                    ->setSmallPicture('picture_small.jpg')
                    ->setPictureAlt(
                        (new TranslatableString)
                        ->setEn('balise alt en anglais')
                        ->setFr('balise alt en français')
                        ->setEs('balise alt en espagnol')
                        ->setIt('balise alt en italien')
                    )
                    ->setMetaDescription(
                        (new TranslatableString)
                        ->setEn('méta-description en anglais')
                        ->setFr('méta-description en français')
                        ->setEs('méta-description en espagnol')
                        ->setIt('méta-description en italien')
                    )
                    ->setShortDescription(
                        (new TranslatableString)
                        ->setEn('description courte en anglais')
                        ->setFr('description courte en français')
                        ->setEs('description courte en espagnol')
                        ->setIt('description courte en italien')
                    )
                    ->setLongHtmlDescription(
                        (new TranslatableText)
                        ->setEn('description longue en anglais')
                        ->setFr('description longue en français')
                        ->setEs('description longue en espagnol')
                        ->setIt('description longue en italien')
                    )
                    ->addSubCategory(
                        (new SubCategory)
                        ->setName(
                            (new TranslatableString)
                            ->setEn('Subcategory 1')
                            ->setFr('Sous-catégorie 1')
                            ->setEs('Sobrecategoria 1')
                            ->setIt('Sopracategoria 1')
                        )
                        ->setSlug(
                            (new TranslatableString)
                            ->setEn('sub-category-1')
                            ->setFr('sous-categorie-1')
                            ->setEs('sobre-categoria-1')
                            ->setIt('sopra-categoria-1')
                        )
                        ->setPicture('picture.jpg')
                        ->setSmallPicture('picture_small.jpg')
                        ->setPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setSmallPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setMetaDescription(
                            (new TranslatableString)
                            ->setEn('méta-description en anglais')
                            ->setFr('méta-description en français')
                            ->setEs('méta-description en espagnol')
                            ->setIt('méta-description en italien')
                        )
                        ->setShortDescription(
                            (new TranslatableString)
                            ->setEn('description courte en anglais')
                            ->setFr('description courte en français')
                            ->setEs('description courte en espagnol')
                            ->setIt('description courte en italien')
                        )
                        ->setLongHtmlDescription(
                            (new TranslatableText)
                            ->setEn('description longue en anglais')
                            ->setFr('description longue en français')
                            ->setEs('description longue en espagnol')
                            ->setIt('description longue en italien')
                        )
                        ->setCreatedAt(new DateTimeImmutable())
                    )
                    ->addSubCategory(
                        (new SubCategory)
                        ->setName(
                            (new TranslatableString)
                            ->setEn('Subcategory 2')
                            ->setFr('Sous-catégorie 2')
                            ->setEs('Sobrecategoria 2')
                            ->setIt('Sopracategoria 2')
                        )
                        ->setSlug(
                            (new TranslatableString)
                            ->setEn('sub-category-2')
                            ->setFr('sous-categorie-2')
                            ->setEs('sobre-categoria-2')
                            ->setIt('sopra-categoria-2')
                        )
                        ->setPicture('picture.jpg')
                        ->setSmallPicture('picture_small.jpg')
                        ->setPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setSmallPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setMetaDescription(
                            (new TranslatableString)
                            ->setEn('méta-description en anglais')
                            ->setFr('méta-description en français')
                            ->setEs('méta-description en espagnol')
                            ->setIt('méta-description en italien')
                        )
                        ->setShortDescription(
                            (new TranslatableString)
                            ->setEn('description courte en anglais')
                            ->setFr('description courte en français')
                            ->setEs('description courte en espagnol')
                            ->setIt('description courte en italien')
                        )
                        ->setLongHtmlDescription(
                            (new TranslatableText)
                            ->setEn('description longue en anglais')
                            ->setFr('description longue en français')
                            ->setEs('description longue en espagnol')
                            ->setIt('description longue en italien')
                        )
                        ->setCreatedAt(new DateTimeImmutable())
                    )
                    ->setCreatedAt(new DateTimeImmutable())
                    ;
        $manager->persist($category);


        $category = (new Category)
                    ->setName(
                        (new TranslatableString)
                        ->setEn('Category 3')
                        ->setFr('Catégorie 3')
                        ->setEs('Categoria 3')
                        ->setIt('Categoria 3')
                    )
                    ->setSlug(
                        (new TranslatableString)
                        ->setEn('category-3')
                        ->setFr('categorie-3')
                        ->setEs('categoria-3')
                        ->setIt('categoria-3')
                    )
                    ->setPicture('picture.jpg')
                    ->setSmallPicture('picture_small.jpg')
                    ->setPictureAlt(
                        (new TranslatableString)
                        ->setEn('balise alt en anglais')
                        ->setFr('balise alt en français')
                        ->setEs('balise alt en espagnol')
                        ->setIt('balise alt en italien')
                    )
                    ->setMetaDescription(
                        (new TranslatableString)
                        ->setEn('méta-description en anglais')
                        ->setFr('méta-description en français')
                        ->setEs('méta-description en espagnol')
                        ->setIt('méta-description en italien')
                    )
                    ->setShortDescription(
                        (new TranslatableString)
                        ->setEn('description courte en anglais')
                        ->setFr('description courte en français')
                        ->setEs('description courte en espagnol')
                        ->setIt('description courte en italien')
                    )
                    ->setLongHtmlDescription(
                        (new TranslatableText)
                        ->setEn('description longue en anglais')
                        ->setFr('description longue en français')
                        ->setEs('description longue en espagnol')
                        ->setIt('description longue en italien')
                    )
                    ->addSubCategory(
                        (new SubCategory)
                        ->setName(
                            (new TranslatableString)
                            ->setEn('Subcategory 1')
                            ->setFr('Sous-catégorie 1')
                            ->setEs('Sobrecategoria 1')
                            ->setIt('Sopracategoria 1')
                        )
                        ->setSlug(
                            (new TranslatableString)
                            ->setEn('sub-category-1')
                            ->setFr('sous-categorie-1')
                            ->setEs('sobre-categoria-1')
                            ->setIt('sopra-categoria-1')
                        )
                        ->setPicture('picture.jpg')
                        ->setSmallPicture('picture_small.jpg')
                        ->setPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setSmallPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setMetaDescription(
                            (new TranslatableString)
                            ->setEn('méta-description en anglais')
                            ->setFr('méta-description en français')
                            ->setEs('méta-description en espagnol')
                            ->setIt('méta-description en italien')
                        )
                        ->setShortDescription(
                            (new TranslatableString)
                            ->setEn('description courte en anglais')
                            ->setFr('description courte en français')
                            ->setEs('description courte en espagnol')
                            ->setIt('description courte en italien')
                        )
                        ->setLongHtmlDescription(
                            (new TranslatableText)
                            ->setEn('description longue en anglais')
                            ->setFr('description longue en français')
                            ->setEs('description longue en espagnol')
                            ->setIt('description longue en italien')
                        )
                        ->setCreatedAt(new DateTimeImmutable())
                    )
                    ->addSubCategory(
                        (new SubCategory)
                        ->setName(
                            (new TranslatableString)
                            ->setEn('Subcategory 2')
                            ->setFr('Sous-catégorie 2')
                            ->setEs('Sobrecategoria 2')
                            ->setIt('Sopracategoria 2')
                        )
                        ->setSlug(
                            (new TranslatableString)
                            ->setEn('sub-category-2')
                            ->setFr('sous-categorie-2')
                            ->setEs('sobre-categoria-2')
                            ->setIt('sopra-categoria-2')
                        )
                        ->setSmallPicture('picture_small.jpg')
                        ->setPicture('picture.jpg')
                        ->setPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setSmallPictureAlt(
                            (new TranslatableString)
                            ->setEn('balise alt en anglais')
                            ->setFr('balise alt en français')
                            ->setEs('balise alt en espagnol')
                            ->setIt('balise alt en italien')
                        )
                        ->setMetaDescription(
                            (new TranslatableString)
                            ->setEn('méta-description en anglais')
                            ->setFr('méta-description en français')
                            ->setEs('méta-description en espagnol')
                            ->setIt('méta-description en italien')
                        )
                        ->setShortDescription(
                            (new TranslatableString)
                            ->setEn('description courte en anglais')
                            ->setFr('description courte en français')
                            ->setEs('description courte en espagnol')
                            ->setIt('description courte en italien')
                        )
                        ->setLongHtmlDescription(
                            (new TranslatableText)
                            ->setEn('description longue en anglais')
                            ->setFr('description longue en français')
                            ->setEs('description longue en espagnol')
                            ->setIt('description longue en italien')
                        )
                        ->setCreatedAt(new DateTimeImmutable())
                    )
                    ->setCreatedAt(new DateTimeImmutable())
                    ;
        $manager->persist($category);

        $manager->flush();
    }
}